### ISSUE TITLE
ACTIVIDAD 7DRS

### ISSUE THREAD

**Issue by ang3-l32** [SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-xd-1#2]

**Comment by ang3-l32** [comment]
[REPORTE_DRS_FUNDINDSOTF_UNIDAD3 actividad 8.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-xd-1/files/10079087/REPORTE_DRS_FUNDINDSOTF_UNIDAD3.actividad.8.pdf)

**Comment by JudithReynaCS** [comment]
CALIFICACION:27%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...

**Comment by ang3-l32** [comment]
[REPORTE_DRS_FUNDINDSOTF_UNIDAD3actividad8-2.pdf](https://github.com/SistemasTecTlaxiaco/actividad-7-documento-de-especificacion-de-requerimientos-equipo-xd-1/files/10079843/REPORTE_DRS_FUNDINDSOTF_UNIDAD3actividad8-2.pdf)
